name: Run Container and Copy Data

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          ref: master  # Change to your main branch

      - name: Create dummy data
        run: |
          mkdir -p TED_Results_From_Container
          echo "This is a dummy file for testing" > TED_Results_From_Container/dummy_file.txt
          echo "Another test file" > TED_Results_From_Container/another_dummy_file.txt

      - name: List contents for debugging
        run: ls -R TED_Results_From_Container

      
