# Comment out the steps you don't need for the rerun
# - name: Checkout repository
#   uses: actions/checkout@v2

# - name: Set up Docker Buildx
#   uses: docker/setup-buildx-action@v2

# - name: Log in to GitHub Container Registry
#   uses: docker/login-action@v2
#   with:
#     registry: ghcr.io
#     username: ${{ github.actor }}
#     password: ${{ secrets.ACTIONS_PAT }}

# - name: Pull Docker image
#   run: docker pull ghcr.io/rtchamna/ted_pipeline:latest

# - name: Run Docker container
#   id: run_container
#   run: docker run --name ted-pipeline-container ghcr.io/rtchamna/ted_pipeline:latest

# - name: Wait for container to finish (optional if needed)
#   run: sleep 60  # Adjust the time based on your container's run time

- name: Checkout the TED_Pipeline_replicate repository
  run: |
    git clone https://github.com/rtchamna/TED_Pipeline_replicate.git
    cd TED_Pipeline_replicate
    git checkout master  # Ensure you are on the master branch

- name: Copy data from container to the replicate repository
  run: |
    mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
    docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container

- name: Commit and push results to the replicate repository
  run: |
    cd TED_Pipeline_replicate
    git config --global user.name 'github-actions[bot]'
    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    git add TED_Results_From_Container
    git commit -m 'Update results from container run'
    git push origin master
