name: Copy Files from Docker Container

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TED_Pipeline_replicate repository
      uses: actions/checkout@v2
      with:
        repository: rtchamna/TED_Pipeline_replicate
        token: ${{ secrets.ACTIONS_PAT }}
        ref: master

    - name: Pull Docker image
      run: docker pull ghcr.io/rtchamna/ted_pipeline:latest

    - name: Run Docker container
      id: run_container
      run: docker run -d --name ted-pipeline-container ghcr.io/rtchamna/ted_pipeline:latest

    - name: Wait for container to finish
      run: docker wait ted-pipeline-container

    - name: Copy data from container to the replicate repository
      run: |
        mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
        docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container
        ls -R TED_Pipeline_replicate/TED_Results_From_Container  # Debugging: List contents to verify copy

    - name: Commit and push results to the replicate repository
      run: |
        cd TED_Pipeline_replicate
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f TED_Results_From_Container/Figures  # Force add ignored files
        git commit -m 'Update results from container run'
        git push origin master

    - name: Clean up container
      run: |
        docker stop ted-pipeline-container
        docker rm ted-pipeline-container
