name: Copy Files from Docker Container

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TED_Pipeline_replicate repository
      uses: actions/checkout@v2
      with:
        repository: rtchamna/TED_Pipeline_replicate
        token: ${{ secrets.ACTIONS_PAT }}
        ref: master

    - name: Start Docker container
      run: |
        docker start ted-pipeline-container

    - name: Copy data from container to the replicate repository
      run: |
        mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
        docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container

    - name: Commit and push results to the replicate repository
      run: |
        cd TED_Pipeline_replicate
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add TED_Results_From_Container
        git commit -m 'Update results from container run'
        git push origin master
