name: Run Container and Copy Data

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          ref: master  # Change to your main branch

      - name: Create dummy file
        run: |
          mkdir -p TED_Results_From_Container
          echo "This is a test file" > TED_Results_From_Container/dummy_file.txt

      - name: List contents for debugging
        run: ls -R TED_Results_From_Container

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git add TED_Results_From_Container
          git commit -m "Add dummy file for testing"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
          git push origin master  # Change to your main branch
