name: Scheduled Job

on:
  schedule:
    # Runs at 8:08 PM UTC (4:08 PM EDT) every day
    - cron: '28 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout primary repository
      uses: actions/checkout@v2
      with:
        path: primary-repo

    - name: Checkout secondary repository
      uses: actions/checkout@v2
      with:
        repository: rtchamna/TED_Pipeline
        token: ${{ secrets.ACTIONS_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r primary-repo/requirements.txt
        pip install -r secondary-repo/requirements.txt

    - name: Run script
      run: |
        cd secondary-repo
        python 0_main_global.py
