name: Run Container and Copy Data

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          ref: master  # Change to your main branch

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.ACTIONS_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull the Docker image
        run: docker pull ghcr.io/rtchamna/ted_pipeline:latest

      - name: Run the Docker container
        run: docker run -d --name ted-pipeline-container ghcr.io/rtchamna/ted_pipeline:latest

      - name: Copy data from container to the repository
        run: |
          mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
          docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container
          ls -R TED_Pipeline_replicate/TED_Results_From_Container  # Debugging: List contents to verify copy

      - name: Commit and push results to the repository
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          cd TED_Pipeline_replicate
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
          git add TED_Results_From_Container/Figures
          git commit -m 'Update results from container run'
          git push origin master

      - name: Clean up container
        run: |
          docker stop ted-pipeline-container
          docker rm ted-pipeline-container
