name: Run Container and Copy Data

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          ref: container

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull the Docker image
        run: docker pull ghcr.io/rtchamna/ted_pipeline:latest

      - name: Run the Docker container
        run: docker run -d --name ted-pipeline-container ghcr.io/rtchamna/ted_pipeline:latest

      - name: Wait for container to finish (optional if needed)
        run: sleep 60  # Adjust the time based on your container's run time

      - name: Checkout the TED_Pipeline_replicate repository
        run: |
          git clone https://github.com/rtchamna/TED_Pipeline_replicate.git
          cd TED_Pipeline_replicate
          git checkout -b container

      - name: Copy data from container to the replicate repository
        run: |
          mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
          docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container

      - name: Commit and push results to the replicate repository
        run: |
          cd TED_Pipeline_replicate
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add TED_Results_From_Container
          git commit -m 'Update results from container run'
          git push origin container
