name: Run Container and Copy Data

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          ref: master  # Change to your main branch

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.ACTIONS_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull the Docker image
        run: docker pull ghcr.io/rtchamna/ted_pipeline:latest

      - name: Run the Docker container
        run: docker run --name ted-pipeline-container ghcr.io/rtchamna/ted_pipeline:latest

      - name: Check container logs (for debugging)
        run: docker logs ted-pipeline-container

      - name: Copy data from container to the repository
        run: |
          mkdir -p TED_Pipeline_replicate/TED_Results_From_Container
          docker cp ted-pipeline-container:/app/Figures TED_Pipeline_replicate/TED_Results_From_Container
          ls -R TED_Pipeline_replicate/TED_Results_From_Container  # Debugging: List contents to verify copy

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          cd TED_Pipeline_replicate
          git add .
          git commit -m "Update results from Docker container"
          git push origin master  # Change to your main branch
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
