name: Duplicate, Run Script, and Retrieve Artifacts

on:
  push:
    branches:
      - master

jobs:
  duplicate-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Duplicate the repository
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        REPO_NAME="TED_Pipeline"
        REPLICATE_NAME="${REPO_NAME}_Replicate"
        USER_NAME="rtchamna"
        TARGET_USER="rtchamna"

        # Create the replicated repository using GitHub API
        curl -H "Authorization: token $ACTIONS_PAT" \
          -d '{"name": "'$REPLICATE_NAME'", "private": true}' \
          https://api.github.com/user/repos

        # Clone the repository using the token
        git clone https://$ACTIONS_PAT@github.com/${USER_NAME}/${REPO_NAME}.git
        cd ${REPO_NAME}
        git remote set-url origin https://$ACTIONS_PAT@github.com/${TARGET_USER}/${REPLICATE_NAME}.git
        git push --set-upstream origin master

    - name: Initialize default branch in the replicated repository
      run: |
        REPO_NAME="TED_Pipeline"
        cd ${REPO_NAME}
        git checkout -b main
        git push origin main

    - name: Run the main script
      run: |
        REPO_NAME="TED_Pipeline"
        cd ${REPO_NAME}
        python 0_main_global.py

    - name: Prepare for artifact upload
      run: |
        mkdir -p artifacts
        mv ${REPO_NAME}/output/* artifacts/  # Adjust the path to your artifacts as needed

    - name: Checkout the replicated repository
      uses: actions/checkout@v2
      with:
        repository: rtchamna/${REPLICATE_NAME}
        token: ${{ secrets.ACTIONS_PAT }}
        path: replicate_repo

    - name: Copy artifacts to replicated repository
      run: |
        cp -r artifacts/* replicate_repo/
        cd replicate_repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add artifacts generated by 0_main_global.py"
        git push origin main
