name: Duplicate, Run Script, and Retrieve Artifacts

on:
  push:
    branches:
      - master

jobs:
  duplicate-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Duplicate the repository
      run: |
        REPO_NAME="TED_Pipeline"
        REPLICATE_NAME="${REPO_NAME}_replicate"
        USER_NAME="rtchamna"
        TARGET_USER="rtchamna"

        # Create the replicated repository using GitHub API
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -d '{"name": "'$REPLICATE_NAME'"}' \
          https://api.github.com/user/repos

        # Mirror the repository
        git clone --mirror https://github.com/${USER_NAME}/${REPO_NAME}.git
        cd ${REPO_NAME}.git
        git remote set-url --push origin https://github.com/${TARGET_USER}/${REPLICATE_NAME}.git
        git push --mirror

    - name: Run the main script
      run: |
        python 0_main_global.py
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPLICATE_NAME: ${{ env.REPLICATE_NAME }}

    - name: Prepare for artifact upload
      run: |
        mkdir -p artifacts
        mv output/* artifacts/  # Adjust the path to your artifacts as needed
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPLICATE_NAME: ${{ env.REPLICATE_NAME }}

    - name: Checkout the replicated repository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.TARGET_USER }}/${{ env.REPLICATE_NAME }}
        token: ${{ secrets.GH_TOKEN }}
        path: replicate_repo

    - name: Copy artifacts to replicated repository
      run: |
        cp -r artifacts/* replicate_repo/
        cd replicate_repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add artifacts generated by 0_main_global.py"
        git push origin main
