name: Duplicate, Run Script, and Retrieve Artifacts

on:
  push:
    branches:
      - master

jobs:
  duplicate-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: List files in the repository
      run: ls -R

    - name: Duplicate the repository
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        REPO_NAME="TED_Pipeline"
        REPLICATE_NAME="${REPO_NAME}_replicate"
        USER_NAME="rtchamna"
        TARGET_USER="rtchamna"

        # Create the replicated repository using GitHub API
        curl -H "Authorization: token $ACTIONS_PAT" \
          -d '{"name": "'$REPLICATE_NAME'", "private": true}' \
          https://api.github.com/user/repos

        # Clone the repository using the token
        git clone --mirror https://$ACTIONS_PAT@github.com/${USER_NAME}/${REPO_NAME}.git
        cd ${REPO_NAME}.git
        git remote set-url --push origin https://$ACTIONS_PAT@github.com/${TARGET_USER}/${REPLICATE_NAME}.git
        git push --mirror

    - name: Run the main script
      run: |
        if [ -f "./0_main_global.py" ]; then
          python 0_main_global.py
        else
          echo "0_main_global.py not found in the root directory"
          exit 1
        fi
      env:
        REPO_NAME: "TED_Pipeline"
        REPLICATE_NAME: "TED_Pipeline_replicate"

    - name: Prepare for artifact upload
      run: |
        mkdir -p artifacts
        mv output/* artifacts/  # Adjust the path to your artifacts as needed
      env:
        REPO_NAME: "TED_Pipeline"
        REPLICATE_NAME: "TED_Pipeline_replicate"

    - name: Checkout the replicated repository
      uses: actions/checkout@v2
      with:
        repository: rtchamna/TED_Pipeline_replicate
        token: ${{ secrets.ACTIONS_PAT }}
        path: replicate_repo

    - name: Copy artifacts to replicated repository
      run: |
        cp -r artifacts/* replicate_repo/
        cd replicate_repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add artifacts generated by 0_main_global.py"
        git push origin main
